Repository AY2324S1-CS2103-F13-3/tp, pull requests merged in 2023-11, with the labels that each got.

#105 Create DeleteVendor feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteVendorCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteVendorCommandParser.java
Labels: priority.Medium, type.Story

#103 Create DeleteVenue feature
  src/main/java/seedu/address/logic/commands/DeleteVenueCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteVenueCommandParser.java
Labels: priority.Medium, type.Story

#106 Feature: Find Event Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CreateEventCommand.java
  src/main/java/seedu/address/logic/commands/CreateVendorCommand.java
  src/main/java/seedu/address/logic/commands/CreateVenueCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindEventCommandParser.java
  src/main/java/seedu/address/model/event/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindEventCommandTest.java
  src/test/java/seedu/address/logic/parser/FindEventCommandParserTest.java
Labels: priority.Medium, type.Story

#104 Feature: Remove person from an event
  src/main/java/seedu/address/logic/commands/RemovePersonCommand.java
  src/main/java/seedu/address/logic/parser/AddEventDetailsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemovePersonCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/RemovePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/RemovePersonCommandParserTest.java
Labels: priority.High, type.Story

#110 Refactor: Add Note to Event Class
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateEventCommandParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Note.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventDetailsDisplay.java
  src/main/resources/view/EventDetailsDisplay.fxml
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.Medium, type.Task

#112 Refactor: Event's Date to FromDate and ToDate
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CreateEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/ViewEventsCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateEventCommandParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/FromDate.java
  src/main/java/seedu/address/model/event/ToDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventDetailsDisplay.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEventCommandTest.java
  src/test/java/seedu/address/logic/parser/CreateEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/displayable/UniqueDisplayableItemListTest.java
  src/test/java/seedu/address/model/event/DateTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/FromDateTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.Medium, type.Task

#114 Documentation: Update User Guide
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: documentation, type.Task

#118 Fix storage issues for vendors
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/ViewVendorsCommandTest.java
Labels: priority.High

#119 Update UserGuide to include v1.3 features
  docs/UserGuide.md
Labels: documentation

#121 Documentation: User Guide v1.3
  docs/UserGuide.md
  docs/images/ViewVendorsUI.png
  docs/images/ViewVenuesUI.png
Labels: documentation

#122 Update messages displayed for invalid commands
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddEventDetailsCommand.java
  src/main/java/seedu/address/logic/commands/CreateEventCommand.java
  src/main/java/seedu/address/logic/commands/CreateVendorCommand.java
  src/main/java/seedu/address/logic/commands/CreateVenueCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVendorCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVenueCommand.java
  src/main/java/seedu/address/logic/commands/EditVendorCommand.java
  src/main/java/seedu/address/logic/commands/EditVenueCommand.java
Labels: type.Bug, severity.Medium

#124 Documentation: Fix UG Bug
  docs/UserGuide.md
Labels: documentation

#126 Bug Fix: RSVP
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, severity.Medium

#151 Gradle: Change mac-aarch64 to mac
  build.gradle
Labels: type.Task

#156 Update UserGuide to fix mistakes identified in PE-D
  docs/UserGuide.md
Labels: documentation, severity.Medium

#170 Fix Bug: To date not displayed in GUI
  src/main/java/seedu/address/model/event/Event.java
Labels: type.Bug, severity.Medium

#177 Fix Bug: RSVP status is not accurately displayed
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/RsvpCommand.java
  src/main/java/seedu/address/logic/commands/ViewEventCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/rsvp/RsvpContainsEventPredicate.java
  src/main/java/seedu/address/ui/EventDetailsDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVenueCommandTest.java
Labels: type.Bug, severity.High, must fix

#178 Bug Fix: RSVP not deleted from storage after `clear` commands
  src/main/java/seedu/address/logic/commands/ClearEventsCommand.java
  src/main/java/seedu/address/logic/commands/ClearGuestsCommand.java
  src/main/java/seedu/address/logic/commands/ClearVendorsCommand.java
  src/main/java/seedu/address/logic/commands/ClearVenuesCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVendorCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateVenueCommandTest.java
Labels: type.Bug, severity.Medium

#181 Bug Fix: Clear commands not updating UI
  src/main/java/seedu/address/logic/commands/ClearEventsCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, severity.Medium

#192 Add test cases for `ModelManager` and `LogicManager`
  src/main/java/seedu/address/model/rsvp/Rsvp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.Medium, type.Task

#193 Add test cases for `RSVP` and `RSVP` Commands
  src/main/java/seedu/address/logic/commands/RsvpCommand.java
  src/main/java/seedu/address/model/rsvp/UniqueRsvpList.java
  src/main/java/seedu/address/storage/JsonAdaptedRsvp.java
  src/test/java/seedu/address/logic/commands/RsvpCommandTest.java
  src/test/java/seedu/address/logic/parser/RsvpCommandParserTest.java
  src/test/java/seedu/address/model/rsvp/RsvpContainsEventPredicateTest.java
  src/test/java/seedu/address/model/rsvp/RsvpStatusTest.java
  src/test/java/seedu/address/model/rsvp/RsvpTest.java
  src/test/java/seedu/address/model/rsvp/UniqueRsvpListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRsvpTest.java
Labels: priority.Medium, type.Task

#194 Update PPP
  docs/team/dom-buri.md
  docs/team/johndoe.md
Labels: documentation

#198 Add Unit Test for `JsonAdaptedVendor`, `JsonAdaptedVenue`
  src/test/java/seedu/address/storage/JsonAdaptedVendorTest.java
  src/test/java/seedu/address/storage/JsonAdaptedVenueTest.java
Labels: priority.Medium, type.Task

#199 Bug Fix: Update UG to align error messages with EventWise
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteVendorCommand.java
  src/main/java/seedu/address/logic/commands/EditVendorCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Note.java
  src/test/java/seedu/address/logic/commands/DeleteVendorCommandTest.java
Labels: type.Bug

#203 Update DG to include Implementations and Manual Testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CreateSequenceDiagram.puml
  docs/diagrams/RSVPSequenceDiagram.puml
  docs/images/CreateSequenceDiagram.png
  docs/images/RSVPSequenceDiagram.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CreateEventCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/venue/Name.java
Labels: documentation

#205 Add Activity Diagram to DG
  docs/DeveloperGuide.md
  docs/diagrams/RsvpActivityDiagram.puml
  docs/images/RsvpActivityDiagram.png
Labels: documentation

#220 Update PPP (Final)
  docs/team/dom-buri.md
Labels: documentation
